name = "nextgridit"
main = "src/worker.ts"
compatibility_date = "2026-03-25"
workers_dev = true
preview_urls = true
keep_vars = true

[assets]
directory = "out"
binding = "ASSETS"
not_found_handling = "404-page"

[[routes]]
pattern = "www.nextgridit.com"
zone_name = "nextgridit.com"
custom_domain = true
